Miguel
nelsonmpg/IPTomar-MEI-IoT-ES pull request #11
Opened 2016-12-17 14:59 UTC by NearDeath

Penso que já esteja.... Eu estava a olhar para o codigo antes de fazer rails db:migrate e estava a pensar: "Eu acho que já vi isto nalgum lado???" carreguei enter e depois de carregar é que me lembrei que tinha feito igual ao anterior xD

2016-12-17 15:15 UTC, renatopanda requested changes
Isto não é suposto estar no git. É a pasta da tua VM. A única coisa que tem de estar no git relacionado com o vagrant é o ficheiro Vagrantfile. Como conseguiste fazer commit disto se no .gitignore está a indicação para ignorar a pasta .vagrant?

2016-12-17 15:34 UTC, NearDeath commented
Magia? XD. Não sei professor. Apenas fiz commite push. Talvez tenha que remover isso da minha pasta do projeto?

2016-12-17 15:36 UTC, renatopanda requested changes
Não está mau, tenho algumas alterações a sugerir para que seja melhorado e obviamente que deve ser testado antes de fazer o merge.

2016-12-17 15:36 UTC, renatopanda commented on ProjectSubmit/app/controllers/schools_controller.rb
>      @schools = School.all
Esta linha é capaz de ser desnecessária, não? Parece-me que já tens um if/else a seguir que define @schools.

2016-12-17 15:36 UTC, renatopanda commented on ProjectSubmit/app/controllers/schools_controller.rb
>    before_action :authenticate_user!
@NearDeath não era mais interessante permitir o acesso a certas acções sem estar autenticado? Qualquer user não registado deve conseguir ver e listar a informação dos projectos. Editar, apagar e criar novos é que obriga ao user estar registado. Concordas?

No fundo é só alterares para `before_filter :authenticate_user!, :except => [:index, :show]`

2016-12-17 15:36 UTC, renatopanda commented on ProjectSubmit/.vagrant/machines/default/virtualbox/private_key
> +-----BEGIN RSA PRIVATE KEY-----
toda a pasta ".vagrant" e respectivos ficheiros devem estar só no teu pc, não devem ser parte dos teus commits e por isso está a informação no .gitignore. Não os deves apagar da **tua** máquina, tens é que os apagar do repositório agora que os enviaste para cá!

2016-12-17 15:36 UTC, renatopanda commented on ProjectSubmit/app/views/schools/index.html.erb
> +  <%= submit_tag "Search", :name => nil %>
Aqui o botão pode dizer "Pesquisar" em vez de "Search", não? Porque razão o :name => nil?

2016-12-17 15:36 UTC, renatopanda commented on ProjectSubmit/app/views/schools/index.html.erb
>        <td><%= link_to 'Editar', edit_school_path(school) %></td>
Podes envolver os botões de editar / remover e até o de criar num bloco para que só sejam mostrados caso o utilizador tenha feito sign in.
```
<% if user_signed_in? %>
(...)
<% end %>
```

2016-12-17 15:42 UTC, renatopanda commented
Não interessa remover da tua pasta local, são as definições da tua VM. Interessa é remover isso do repositório, para que cada um tenha a sua própria pasta. Vê as outras alterações primeiro e depois já vês isso.

2016-12-17 15:53 UTC, NearDeath commented
Já fiz todas as alterações excepto aquilo do .vagrant:

Como apago daqui?

2016-12-17 15:55 UTC, NearDeath commented on ProjectSubmit/app/views/schools/index.html.erb
> +  <%= submit_tag "Search", :name => nil %>
sem o :name >nil não funciona. Tenho depois de ver porque

2016-12-17 16:09 UTC, renatopanda commented
Na linha de comandos, na pasta do projecto: `git rm -r --cached .vagrant` funciona?

2016-12-17 16:10 UTC, NearDeath commented
Pela git bash certo?

2016-12-17 16:11 UTC, renatopanda commented
Pode ser.

2016-12-17 16:13 UTC, NearDeath commented
![screenshot_1](https://cloud.githubusercontent.com/assets/17543952/21288177/cb3b2626-c473-11e6-87de-63d53ab62df8.png)

Penso que sim

2016-12-17 16:20 UTC, renatopanda requested changes
Acho que só falta colocares os "Mostrar" fora do `if`, testares convenientemente com o user logado e não logado, ver se consegue ou não aceder ao que deve e já é altura de terem uma página qualquer definida como root (até pode ser a dos schools#index ou projects)

2016-12-17 16:20 UTC, renatopanda commented on ProjectSubmit/app/views/courses/index.html.erb
>        <td><%= link_to 'Mostrar', course_path(course) %></td>
O mostrar pode ficar de fora do `if`, não?
Isto para os três index.html.erb que submeteste

2016-12-17 16:42 UTC, renatopanda submitted a review, later dismissed

2016-12-17 17:05 UTC, renatopanda requested changes
Testei isto em 3 minutos na vm e existem 3 problemas:
1. as validações têm que ser mais claras.  "O campo não pode estar vazio" não me diz nada. Se for "O nome da escola não pode estar vazio" ou algo mais correcto então sim, faz sentido.

2. Seeds seeds seeds! Para eu testar tenho que ter coisas na BD. É essencial que o ficheiro db/seeds.rb carregue valores decentes para a base de dados. @NearDeath adiciona / actualiza isso para os teus modelos.

3. Não sei fazer signout, descobri que posso fazer na página dos projectos mas o link não funciona (a rota não existe, por estar a enviar por get e não por post/delete).

De resto funciona bem e pode ser feito o merge depois de corrigidos 1 e 2.

2016-12-17 17:05 UTC, renatopanda commented on ProjectSubmit/app/models/school.rb
>      validates :description, presence: { message: "O campo não pode ser vazio." },
Qual campo? As mensagens de erro são muito pouco claras, ao testar nem percebi onde estava o erro.

2016-12-18 21:24 UTC, renatopanda commented
@NearDeath uma pergunta antes de aprovar isto. Porque é que no último commit, no ficheiro seeds.rb, comentaste a inserção de Documents e Persons? O ideal é ter um seeds.rb que encha todas as tabelas com casos possíveis para testar. Se estavam errados o ideal é corrigires isso e adicionar mais, não?

2016-12-18 21:27 UTC, NearDeath commented
Porque existe um problema. Existe um incongruência entre person e propor numa tabela e não me deixava criar as seeds

2016-12-18 21:29 UTC, renatopanda commented
Não percebi mas não é problemático, é uma tarefa a fazer ASAP. Adicionar seeds para tudo.

2016-12-18 21:29 UTC, renatopanda approved these changes

2016-12-18 21:31 UTC, merged